// NOTE:
// The values included here are taken from the original google doc.
// Each sound and its associated data is put between curly braces {}/

// To edit any value, make sure that the new value is placed between the quotation marks. Please also make sure that each line inside the curly braces ends in a comma.

// Do not edit in a rich text program like MS Word. Use a program like VisualStudioCode (which is a free download). You could also use a program like TextEdit on Mac or NotePad on Windows, as long as you make sure that it is saving in plaintext format. An advantage of VisualStudioCode, however, is that it will use color to signify each part, which makes it easier to keep consistent syntax.

const malay = [
  {
    soundNum: 1,
    sound: "01siamix.mp3",
    text: "kadang-kadang aku",
    synonym: "keseorangan",
  },
  {
    soundNum: 2,
    sound: "02sia-mentor.mp3",
    text: "kadang-kadang aku",
    synonym: "halimunan",
  },
  {
    soundNum: 3,
    sound: "03sia-school.mp3",
    text: "kadang-kadang aku",
    synonym: "jauh",
  },
  {
    soundNum: 4,
    sound: "04siasq2.mp3",
    text: "kadang-kadang aku",
    synonym: "tak mempunyai apa-apa",
  },
  {
    soundNum: 5,
    sound: "05sia-class.mp3",
    text: "kadang-kadang aku",
    synonym: "bukan seorang",
  },
  {
    soundNum: 6,
    sound: "06weare-mix.mp3",
    text: "kami",
    synonym: "puas hati",
  },
  {
    soundNum: 7,
    sound: "07weare-chrous.mp3",
    text: "kita",
    synonym: "berbeza",
  },
  {
    soundNum: 8,
    sound: "08theyare-mix.mp3",
    text: "dia orang",
    synonym: "ghaib",
  },
  {
    soundNum: 9,
    sound: "09theyare-def.mp3",
    text: "dia orang",
    synonym: "dah pergi",
  },
  {
    soundNum: 10,
    sound: "10wecan-def.mp3",
    text: "kita boleh",
    synonym: "bebas",
  },
  {
    soundNum: 11,
    sound: "11wecan-grrl.mp3",
    text: "kita boleh",
    synonym: "wujud",
  },
  {
    soundNum: 12,
    sound: "12wecan-mx2.mp3",
    text: "kita boleh ke?",
    synonym: "kita boleh",
  },
  {
    soundNum: 13,
    sound: "13wecan-maybeX.mp3",
    text: "dia orang boleh",
    synonym: "tersembunyi",
  },
  {
    soundNum: 14,
    sound: "14theycan.mp3",
    text: "dia orang boleh",
    synonym: "",
  },
  {
    soundNum: 15,
    sound: "15theycan-whatever.mp3",
    text: "dia orang boleh",
    synonym: "mereka tak boleh",
  },
  {
    soundNum: 16,
    sound: "16wecan-sador.mp3",
    text: "kita tak boleh",
    synonym: "tak mempunyai apa-apa",
  },
  {
    soundNum: 17,
    sound: "17wecan-sadL.mp3",
    text: "kita tak boleh",
    synonym: "susah",
  },
  {
    soundNum: 18,
    sound: "18youare-praise.mp3",
    text: "kamu",
    synonym: "bukan seorang",
  },
  {
    soundNum: 19,
    sound: "19youare-grppraise.mp3",
    text: "kamu",
    synonym: "wujud",
  },
  {
    soundNum: 20,
    sound: "20youare-accuse.mp3",
    text: "kamu",
    synonym: "tiada apa pun",
  },
  {
    soundNum: 21,
    sound: "21youare-ess.mp3",
    text: "kamu",
    synonym: "kecil",
  },
  {
    soundNum: 22,
    sound: "22beyou-scn.mp3",
    text: "jadilah diri sendiri",
    synonym: "tersembunyi",
  },
  {
    soundNum: 23,
    sound: "23beyou-girl.mp3",
    text: "jadilah diri sendiri",
    synonym: "lihat aku",
  },
  {
    soundNum: 24,
    sound: "24beyou-plz.mp3",
    text: "jadilah diri sendiri",
    synonym: "kuat",
  },
  {
    soundNum: 25,
    sound: "25bethem-mix.mp3",
    text: "jadilah seperti mereka",
    synonym: "aku tak boleh",
  },
  {
    soundNum: 26,
    sound: "26bethem-if.mp3",
    text: "jadilah seperti mereka",
    synonym: "berpura-pura",
  },
  {
    soundNum: 27,
    sound: "27invis.mp3",
    text: "halimunan",
    synonym: "tak kelihatan",
  },
  {
    soundNum: 28,
    sound: "28invis-soft.mp3",
    text: "halimunan",
    synonym: "hilang",
  },
  {
    soundNum: 29,
    sound: "29invis-snap.mp3",
    text: "tak kelihatan",
    synonym: "ghaib",
  },
  {
    soundNum: 30,
    sound: "30invis-syl.mp3",
    text: "tak kelihatan",
    synonym: "sudah pergi",
  },
  {
    soundNum: 31,
    sound: "31inviswhisper.mp3",
    text: "halimunan",
    synonym: "lihat aku",
  },
  {
    soundNum: 32,
    sound: "32invis.mp3",
    text: "halimunan",
    synonym: "keseorangan",
  },
  {
    soundNum: 33,
    sound: "33invisloud.mp3",
    text: "",
    synonym: "kesemuanya",
  },
  {
    soundNum: 34,
    sound: "34invissad.mp3",
    text: "halimunan",
    synonym: "takut",
  },
  {
    soundNum: 35,
    sound: "35invistaunt.mp3",
    text: "halimunan",
    synonym: "tak ada di sini",
  },
  {
    soundNum: 36,
    sound: "36seethem.mp3",
    text: "lihatlah mereka",
    synonym: "berbeza",
  },
  {
    soundNum: 37,
    sound: "37seethem-loser.mp3",
    text: "lihatlah mereka",
    synonym: "kecil",
  },
  {
    soundNum: "38",
    sound: "38seeme-look.mp3",
    text: "lihatlah aku",
    synonym: "lihat aku",
  },
  {
    soundNum: "39",
    sound: "39seeme-mix.mp3",
    text: "lihatlah aku",
    synonym: "puas hati",
  },
  {
    soundNum: "40",
    sound: "40sia-mix.mp3",
    text: "kadang-kadang aku",
    synonym: "sedih",
  },
  {
    soundNum: "41",
    sound: "41sia-explan.mp3",
    text: "kadang-kadang aku",
    synonym: "jauh",
  },
  {
    soundNum: "42",
    sound: "42seeyou.mp3",
    text: "nampak kamu",
    synonym: "tiada apa pun",
  },
  {
    soundNum: "43",
    sound: "43seeyou-whatever.mp3",
    text: "nampak kamu",
    synonym: "sedih",
  },
  {
    soundNum: "44",
    sound: "44theyare-invismix.mp3",
    text: "dia orang",
    synonym: "bukan seorang",
  },
  {
    soundNum: "45",
    sound: "45theyare-mix.mp3",
    text: "dia orang",
    synonym: "di sini",
  },
  {
    soundNum: "46",
    sound: "46seethem-comm.mp3",
    text: "tengok dia orang",
    synonym: "mereka tak boleh",
  },
  {
    soundNum: "47",
    sound: "47seethem-echo.mp3",
    text: "tengok dia orang",
    synonym: "hilang",
  },
  {
    soundNum: "48",
    sound: "48youcant-sad.mp3",
    text: "kamu tak boleh",
    synonym: "susah",
  },
  {
    soundNum: "49",
    sound: "49youcant-stern.mp3",
    text: "kamu tak boleh",
    synonym: "takut",
  },
  {
    soundNum: "50",
    sound: "50youcant-dont.mp3",
    text: "kamu tak boleh",
    synonym: "tiada apa pun",
  },
  {
    soundNum: "51",
    sound: "51theycant-lament.mp3",
    text: "dia orang",
    synonym: "tak boleh",
  },
  {
    soundNum: "52",
    sound: "52theycant-emph.mp3",
    text: "dia orang tak boleh",
    synonym: "dia orang tak hadir",
  },
  {
    soundNum: "53",
    sound: "53iam-ghostmix.mp3",
    text: "Aku",
    synonym: "dah pergi",
  },
  {
    soundNum: "54",
    sound: "54iamecho.mp3",
    text: "Aku",
    synonym: "tak boleh",
  },
  {
    soundNum: "55",
    sound: "55youcantseeme-sad.mp3",
    text: "kau tak dapat lihat",
    synonym: "",
  },
  {
    soundNum: "56",
    sound: "56youcantseeme-tween.mp3",
    text: "kau tak dapat lihat",
    synonym: "aku langsung",
  },
  {
    soundNum: "57",
    sound: "57youcantforbid.mp3",
    text: "kau tak boleh",
    synonym: "",  },
  {
    soundNum: "58",
    sound: "58iam-sure.mp3",
    text: "aku",
    synonym: "puas hati",
  },
  {
    soundNum: "59",
    sound: "59iam-def.mp3",
    text: "aku",
    synonym: "hiba",
  },
  {
    soundNum: "60",
    sound: "60iam-girl.mp3",
    text: "aku",
    synonym: "berbezaberbeza",
  },
  {
    soundNum: "61",
    sound: "61iam.mp3",
    text: "aku",
    synonym: "mereka",
  },
  {
    soundNum: "62",
    sound: "62iam-whatever.mp3",
    text: "aku",
    synonym: "jauh",
  },
  {
    soundNum: "63",
    sound: "63seethem-whis.mp3",
    text: "tengok dia orang",
    synonym: "halimunan",
  },
  {
    soundNum: "64",
    sound: "64seethem-outrage.mp3",
    text: "tengok dia orang",
    synonym: "lihat aku",
  },
  {
    soundNum: "65",
    sound: "65youare-confess.mp3",
    text: "kamu",
    synonym: "keseorangan",
  },
  {
    soundNum: "66",
    sound: "66youaredef.mp3",
    text: "kamu",
    synonym: "keseorangan",
  },
  {
    soundNum: "67",
    sound: "67nobodyseesme-sad.mp3",
    text: "tiada siapapun",
    synonym: "yang lihat aku",
  },
  {
    soundNum: "68",
    sound: "68nobodyseesme-girl.mp3",
    text: "",
    synonym: "halimunan",
  },
  {
    soundNum: "69",
    sound: "69nobdoyseesme-control.mp3",
    text: "tiada siapapun yang lihat aku",
    synonym: "",
  },
  {
    soundNum: "70",
    sound: "70nobodyseesme-inform.mp3",
    text: "",
    synonym: "tengok aku",
  },
  {
    soundNum: "71",
    sound: "71beme.mp3",
    text: "jadilah aku",
    synonym: "",
  },
  {
    soundNum: "72",
    sound: "72beme-soft.mp3",
    text: "jadilah aku",
    synonym: "seperti kamu",
  },
  {
    soundNum: "73",
    sound: "73sia-confess.mp3",
    text: "kadang-kadang aku",
    synonym: "tak boleh",
  },
  {
    soundNum: "74",
    sound: "74sia-confess.mp3",
    text: "kadang-kadang aku",
    synonym: "tersembunyi",
  },
];

export default malay;
