export const SITENAMES = {
  en: "sometimes i am",
  fr: "parfois je suis",
  ja: "ときどき わたしは",
  it: "a volte io sono",
  es: "a veces yo soy",
  fa: "بعضی وقت ها من",
  ur: "کبھی کبھی میں",
  de: "manchmal bin ich",
  ko: "이따금 나는",
  ms: "kadang-kadang aku",
}

export const INSTRUCTIONS = {
  en: "go ahead: click somewhere...",
  fr: "allez-y: cliquez n'importe où...",
  ja: "どこでもクリックしてください。",
  it: "fai clic su un punto qualsiasi",
  es: "cliquear en cualquier lugar de la pantalla",
  fa: "شروع کن: هرجا (یا روی هرنقطه) کلیک کن",
  ur: "آگے بڑھیں: کہیں بھی کلک کریں...",
  de: "los geht's: klick irgendwo",
  ko: "해보세요: 아무곳이나 눌러보세요 (클릭, 터치)",
  ms: "dipersilakan: klik di mana-mana tempat",
}

export const PREFERENCES_TEXT = {
  en: {
    polyglotTrigger: "Polyglot mode: start threshold",
    polyglotEnd: "Polyglot mode: end threshold",
    maxPolyglotNodes: "Polyglot mode: maximum text nodes",
    maxFZMessage: "Main Primary Text: maximum font size",
    maxFZSynonym: "Main Secondary Text: maximum font size",
    maxFZMessageNode: "Polyglot mode primary text: maximum font size",
    maxFZSynonymNode: "Polyglot mode secondary text: maximum font size",
    baseVolume: "Base volume",
    fadeFactor: "Fade factor",
    minVolume: "Minimum volume",
    nodeOpacityBtmLimit: "Polyglot mode primary text: opacity lower limit",
    nodeOpacityTopLimit: "Polyglot mode secondary text: opacity upper limit",
    hideMainTextAtPolyglot: "Hide main text during polyglot mode",
    colorsMode: "Colors mode",
    maxRotation: "Polyglot mode: maximum text rotation",
    "reset-to-defaults": "Reset to defaults",
  },
  fr: {
    polyglotTrigger: "Mode polyglotte : seuil de départ",
    polyglotEnd: "Mode polyglotte : seuil de fin",
    maxPolyglotNodes: "Mode polyglotte : nombre maximum de nœuds de texte",
    maxFZMessage: "Texte principal primaire : taille de police maximale",
    maxFZSynonym: "Texte principal secondaire : taille de police maximale",
    maxFZMessageNode: "Mode polyglotte texte primaire : taille de police maximale",
    maxFZSynonymNode: "Mode polyglotte texte secondaire : taille de police maximale",
    baseVolume: "Volume de base",
    fadeFactor: "Facteur d'atténuation",
    minVolume: "Volume minimum",
    nodeOpacityBtmLimit: "Mode polyglotte texte primaire : limite inférieure d'opacité",
    nodeOpacityTopLimit: "Mode polyglotte texte secondaire : limite supérieure d'opacité",
    hideMainTextAtPolyglot: "Masquer le texte principal en mode polyglotte",
    colorsMode: "Mode couleurs",
    maxRotation: "Mode polyglotte : rotation maximale du texte",
    "reset-to-defaults": "Réinitialiser par défaut",
  },
  ja: {
    polyglotTrigger: "多言語モード：開始しきい値",
    polyglotEnd: "多言語モード：終了しきい値",
    maxPolyglotNodes: "多言語モード：テキストノードの最大数",
    maxFZMessage: "メイン主要テキスト：最大フォントサイズ",
    maxFZSynonym: "メイン副テキスト：最大フォントサイズ",
    maxFZMessageNode: "多言語モード 主要テキスト：最大フォントサイズ",
    maxFZSynonymNode: "多言語モード 副テキスト：最大フォントサイズ",
    baseVolume: "基本音量",
    fadeFactor: "フェード係数",
    minVolume: "最小音量",
    nodeOpacityBtmLimit: "多言語モード 主要テキスト：不透明度の下限",
    nodeOpacityTopLimit: "多言語モード 副テキスト：不透明度の上限",
    hideMainTextAtPolyglot: "多言語モード中はメインテキストを非表示",
    colorsMode: "カラーモード",
    maxRotation: "多言語モード：テキストの最大回転角",
    "reset-to-defaults": "既定値にリセット",
  },
  it: {
    polyglotTrigger: "Modalità poliglotta: soglia di inizio",
    polyglotEnd: "Modalità poliglotta: soglia di fine",
    maxPolyglotNodes: "Modalità poliglotta: nodi di testo massimi",
    maxFZMessage: "Testo principale primario: dimensione massima carattere",
    maxFZSynonym: "Testo principale secondario: dimensione massima carattere",
    maxFZMessageNode: "Modalità poliglotta testo primario: dimensione massima carattere",
    maxFZSynonymNode: "Modalità poliglotta testo secondario: dimensione massima carattere",
    baseVolume: "Volume di base",
    fadeFactor: "Fattore di attenuazione",
    minVolume: "Volume minimo",
    nodeOpacityBtmLimit: "Modalità poliglotta testo primario: limite inferiore di opacità",
    nodeOpacityTopLimit: "Modalità poliglotta testo secondario: limite superiore di opacità",
    hideMainTextAtPolyglot: "Nascondi il testo principale in modalità poliglotta",
    colorsMode: "Modalità colori",
    maxRotation: "Modalità poliglotta: rotazione massima del testo",
    "reset-to-defaults": "Ripristina valori predefiniti",
  },
  es: {
    polyglotTrigger: "Modo políglota: umbral de inicio",
    polyglotEnd: "Modo políglota: umbral de fin",
    maxPolyglotNodes: "Modo políglota: nodos de texto máximos",
    maxFZMessage: "Texto principal primario: tamaño máximo de fuente",
    maxFZSynonym: "Texto principal secundario: tamaño máximo de fuente",
    maxFZMessageNode: "Modo políglota texto primario: tamaño máximo de fuente",
    maxFZSynonymNode: "Modo políglota texto secundario: tamaño máximo de fuente",
    baseVolume: "Volumen base",
    fadeFactor: "Factor de desvanecimiento",
    minVolume: "Volumen mínimo",
    nodeOpacityBtmLimit: "Modo políglota texto primario: límite inferior de opacidad",
    nodeOpacityTopLimit: "Modo políglota texto secundario: límite superior de opacidad",
    hideMainTextAtPolyglot: "Ocultar el texto principal en modo políglota",
    colorsMode: "Modo colores",
    maxRotation: "Modo políglota: rotación máxima del texto",
    "reset-to-defaults": "Restablecer valores predeterminados",
  },
  fa: {
    polyglotTrigger: "حالت چندزبانه: آستانهٔ شروع",
    polyglotEnd: "حالت چندزبانه: آستانهٔ پایان",
    maxPolyglotNodes: "حالت چندزبانه: حداکثر گره‌های متنی",
    maxFZMessage: "متن اصلیِ اولیه: حداکثر اندازهٔ فونت",
    maxFZSynonym: "متن اصلیِ ثانویه: حداکثر اندازهٔ فونت",
    maxFZMessageNode: "حالت چندزبانه متن اولیه: حداکثر اندازهٔ فونت",
    maxFZSynonymNode: "حالت چندزبانه متن ثانویه: حداکثر اندازهٔ فونت",
    baseVolume: "بلندی صدای پایه",
    fadeFactor: "ضریب محوشدن",
    minVolume: "حداقل بلندی صدا",
    nodeOpacityBtmLimit: "حالت چندزبانه متن اولیه: حد پایین شفافیت",
    nodeOpacityTopLimit: "حالت چندزبانه متن ثانویه: حد بالای شفافیت",
    hideMainTextAtPolyglot: "پنهان‌کردن متن اصلی در حالت چندزبانه",
    colorsMode: "حالت رنگ‌ها",
    maxRotation: "حالت چندزبانه: حداکثر چرخش متن",
    "reset-to-defaults": "بازنشانی به پیش‌فرض‌ها",
  },
  ur: {
    polyglotTrigger: "کثیراللسانی موڈ: آغاز کی حد",
    polyglotEnd: "کثیراللسانی موڈ: اختتام کی حد",
    maxPolyglotNodes: "کثیراللسانی موڈ: زیادہ سے زیادہ متن نوڈز",
    maxFZMessage: "مرکزی بنیادی متن: زیادہ سے زیادہ فونٹ سائز",
    maxFZSynonym: "مرکزی ثانوی متن: زیادہ سے زیادہ فونٹ سائز",
    maxFZMessageNode: "کثیراللسانی موڈ بنیادی متن: زیادہ سے زیادہ فونٹ سائز",
    maxFZSynonymNode: "کثیراللسانی موڈ ثانوی متن: زیادہ سے زیادہ فونٹ سائز",
    baseVolume: "بنیادی والیوم",
    fadeFactor: "فیڈ فیکٹر",
    minVolume: "کم از کم والیوم",
    nodeOpacityBtmLimit: "کثیراللسانی موڈ بنیادی متن: شفافیت کی نچلی حد",
    nodeOpacityTopLimit: "کثیراللسانی موڈ ثانوی متن: شفافیت کی بالائی حد",
    hideMainTextAtPolyglot: "کثیراللسانی موڈ میں مرکزی متن چھپائیں",
    colorsMode: "رنگ موڈ",
    maxRotation: "کثیراللسانی موڈ: زیادہ سے زیادہ متن گردش",
    "reset-to-defaults": "ڈیفالٹس پر ری سیٹ کریں",
  },
  de: {
    polyglotTrigger: "Vielsprachiger Modus: Startschwelle",
    polyglotEnd: "Vielsprachiger Modus: Endschwelle",
    maxPolyglotNodes: "Vielsprachiger Modus: maximale Textknoten",
    maxFZMessage: "Haupttext primär: maximale Schriftgröße",
    maxFZSynonym: "Haupttext sekundär: maximale Schriftgröße",
    maxFZMessageNode: "Vielsprachiger Modus Text primär: maximale Schriftgröße",
    maxFZSynonymNode: "Vielsprachiger Modus Text sekundär: maximale Schriftgröße",
    baseVolume: "Basislautstärke",
    fadeFactor: "Fade-Faktor",
    minVolume: "Mindestlautstärke",
    nodeOpacityBtmLimit: "Vielsprachiger Modus Text primär: untere Deckkraftgrenze",
    nodeOpacityTopLimit: "Vielsprachiger Modus Text sekundär: obere Deckkraftgrenze",
    hideMainTextAtPolyglot: "Haupttext im vielsprachigen Modus ausblenden",
    colorsMode: "Farbmodus",
    maxRotation: "Vielsprachiger Modus: maximale Textrotation",
    "reset-to-defaults": "Auf Standardwerte zurücksetzen",
  },
  ko: {
    polyglotTrigger: "다언어 모드: 시작 임계값",
    polyglotEnd: "다언어 모드: 종료 임계값",
    maxPolyglotNodes: "다언어 모드: 최대 텍스트 노드 수",
    maxFZMessage: "메인 기본 텍스트: 최대 글꼴 크기",
    maxFZSynonym: "메인 보조 텍스트: 최대 글꼴 크기",
    maxFZMessageNode: "다언어 모드 기본 텍스트: 최대 글꼴 크기",
    maxFZSynonymNode: "다언어 모드 보조 텍스트: 최대 글꼴 크기",
    baseVolume: "기본 볼륨",
    fadeFactor: "페이드 계수",
    minVolume: "최소 볼륨",
    nodeOpacityBtmLimit: "다언어 모드 기본 텍스트: 불투명도 하한",
    nodeOpacityTopLimit: "다언어 모드 보조 텍스트: 불투명도 상한",
    hideMainTextAtPolyglot: "다언어 모드에서 메인 텍스트 숨기기",
    colorsMode: "색상 모드",
    maxRotation: "다언어 모드: 최대 텍스트 회전",
    "reset-to-defaults": "기본값으로 재설정",
  },
  ms: {
    polyglotTrigger: "Mod poliglot: ambang permulaan",
    polyglotEnd: "Mod poliglot: ambang tamat",
    maxPolyglotNodes: "Mod poliglot: maksimum nod teks",
    maxFZMessage: "Teks utama primer: saiz fon maksimum",
    maxFZSynonym: "Teks utama sekunder: saiz fon maksimum",
    maxFZMessageNode: "Mod poliglot teks primer: saiz fon maksimum",
    maxFZSynonymNode: "Mod poliglot teks sekunder: saiz fon maksimum",
    baseVolume: "Kelantangan asas",
    fadeFactor: "Faktor pudar",
    minVolume: "Kelantangan minimum",
    nodeOpacityBtmLimit: "Mod poliglot teks primer: had bawah kelegapan",
    nodeOpacityTopLimit: "Mod poliglot teks sekunder: had atas kelegapan",
    hideMainTextAtPolyglot: "Sembunyikan teks utama semasa mod poliglot",
    colorsMode: "Mod warna",
    maxRotation: "Mod poliglot: putaran teks maksimum",
    "reset-to-defaults": "Tetapkan semula kepada lalai",
  },
}
